name: 'Push Docker to GCP'
description: 'Push docker image to Google Artifact Registry'
branding:
  color: 'green'
  icon: 'box'
inputs:
  gcr_host:
    description: 'Google Artifact Registry Host'
    default: 'asia-south1-docker.pkg.dev'
  image_name:
    description: 'Docker Image Name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
